# Use the official Deno image as the base image
FROM denoland/deno:2.1.4

ARG TIMEZONE=America/Curacao    
ENV TZ ${TIMEZONE}

RUN apt-get update && apt-get install -y tzdata && \
    ln -fs /usr/share/zoneinfo/$TZ /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy the required files into the container
# You may want to change this depending on your project structure
COPY deno.json .
COPY deno.lock .

RUN deno install
COPY . .

RUN deno cache ./src/main.js
# Specify the start command
# Change "your_start_file.ts" to the entry file of your application
CMD ["deno",  "run", "dev"]


